### ISSUE TITLE
Use golang.org/x/sys/cpu for CPU feature detection?

### ISSUE THREAD

**Issue by mengzhuo** [mmcloughlin/meow#15]
We can use https://godoc.org/golang.org/x/sys/cpu .

**Comment by mmcloughlin** [comment]
Thanks for filing this issue. There are two reasons why I didn't do this.

Firstly I need to check for CPUID flags that are unsupported by `x/sys/cpu`.

https://github.com/mmcloughlin/meow/blob/871e50784daff1c9ec5ef66fe3d8fda6bbcd42cf/dispatch_amd64.go#L5-L16

Second, for a library such as this, I prefer to avoid dependencies unless strictly necessary.

**Comment by mengzhuo** [comment]
I see.
I'm trying porting meow's  ARMv8( arm64 ).
However it will be painful that implement arm64's CPU feature detection on its own.

**Comment by mmcloughlin** [comment]
I would welcome an ARMv8 pull request. If `golang.org/x/sys/cpu` provides the feature detection you need, it would be fine to use it. We would still need to use custom code for x86.
