### ISSUE TITLE
Implement the standard Go Hash interface

### ISSUE THREAD

**Issue by tidwall** [mmcloughlin/meow#8]
Do you think it might be possible to implement the standard `hash.Hash`, `hash.Hash32`, and `hash.Hash64` interfaces. Then meow could be a drop-in replacement for many cases.

https://golang.org/pkg/hash/#Hash

**Comment by mmcloughlin** [comment]
The reason not to do this was that the length was part of the initialization vector, making streaming difficult. See cmuratori/meow_hash#2 for discussion.

Having just checked that issue, it seems he's come up with a v0.2 to address this problem. I'll adopt this change once it's finalized.
